#!/bin/bash

# Job name
#SBATCH --job-name=test_1

# Number pf nodes
#SBATCH --nodes=1

# Number of processor per node
#SBATCH --nstacks-per-node=16

# Nomber of RAM per node
#SBATCH --mem=500Go

# Type of machines requested (type1 or 2)
#SBATCH --partition=type_1

# Name of output file
#SBATCH --output=test_1.out

# Calculation times
#SBATCH --time=10-00:00:00

# loading modules
module load userspace/tr17.10
modue load python/3.6.3




########### script ##########
date
echo -e "\nStart calcul cubs\n"

path_folder_pID=(/mnt/beegfs/pturk/PID_couple)

cd /trinity/home/pturk
python3 ./scriptCubs.py $path_folder_pID
date

echo -e "\nDone\n"